version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      groups:
          vitest:
              patterns:
                  - "@vitest/*"
                  - "vitest"
          protobuf-ts:
              patterns:
                  - "@protobuf-ts/*"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
