services:
    frontend:
        build:
            context: .
        environment:
            NODE_ENV: production
            PORT: ${PORT:-4173}
            PUBLIC_API_BASE_URL: ${PUBLIC_API_BASE_URL}
            PUBLIC_CREDENTIAL_POLICY: include
        ports:
            - ${PORT:-4173}:${PORT:-4173}
