services:
    # Chromium setup
    frontend-chromium:
        build:
            context: .
        environment:
            NODE_ENV: production
            PORT: ${FRONTEND_PORT_CHROMIUM:-4187}
            PUBLIC_API_BASE_URL: http://localhost:${MOCK_BACKEND_PORT_CHROMIUM:-3002}
        ports:
            - ${FRONTEND_PORT_CHROMIUM:-4187}:${FRONTEND_PORT_CHROMIUM:-4187}
        depends_on:
            - mock-backend-chromium
        profiles:
            - chromium

    mock-backend-chromium:
        image: ghcr.io/se-uulm/snowballr-mock-backend:main
        environment:
            NODE_ENV: production
            GRPC_WEB_PORT: ${MOCK_BACKEND_PORT_CHROMIUM:-3002}
        ports:
            - ${MOCK_BACKEND_PORT_CHROMIUM:-3002}:${MOCK_BACKEND_PORT_CHROMIUM:-3002}
        profiles:
            - chromium

    # Firefox setup
    frontend-firefox:
        build:
            context: .
        environment:
            NODE_ENV: production
            PORT: ${FRONTEND_PORT_FIREFOX:-4188}
            PUBLIC_API_BASE_URL: http://localhost:${MOCK_BACKEND_PORT_FIREFOX:-3003}
        ports:
            - ${FRONTEND_PORT_FIREFOX:-4188}:${FRONTEND_PORT_FIREFOX:-4188}
        depends_on:
            - mock-backend-firefox
        profiles:
            - firefox

    mock-backend-firefox:
        image: ghcr.io/se-uulm/snowballr-mock-backend:main
        environment:
            NODE_ENV: production
            GRPC_WEB_PORT: ${MOCK_BACKEND_PORT_FIREFOX:-3003}
        ports:
            - ${MOCK_BACKEND_PORT_FIREFOX:-3003}:${MOCK_BACKEND_PORT_FIREFOX:-3003}
        profiles:
            - firefox

    # Webkit setup
    frontend-webkit:
        build:
            context: .
        environment:
            NODE_ENV: production
            PORT: ${FRONTEND_PORT_WEBKIT:-4189}
            PUBLIC_API_BASE_URL: http://localhost:${MOCK_BACKEND_PORT_WEBKIT:-3004}
        ports:
            - ${FRONTEND_PORT_WEBKIT:-4189}:${FRONTEND_PORT_WEBKIT:-4189}
        depends_on:
            - mock-backend-webkit
        profiles:
            - webkit

    mock-backend-webkit:
        image: ghcr.io/se-uulm/snowballr-mock-backend:main
        environment:
            NODE_ENV: production
            GRPC_WEB_PORT: ${MOCK_BACKEND_PORT_WEBKIT:-3004}
        ports:
            - ${MOCK_BACKEND_PORT_WEBKIT:-3004}:${MOCK_BACKEND_PORT_WEBKIT:-3004}
        profiles:
            - webkit
