name: Setup
description: Setup Frontend CI/CD pipeline
runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
              node-version: 22

        - name: Install dependencies
          shell: bash
          run: npm ci

        - name: Svelte-Kit sync
          shell: bash
          run: npx svelte-kit sync
