name: Bug report
description: Create a bug report to help us improve the project
title: "[Bug]: <title>"
labels: ["bug"]
projects: ["SE-UUlm/2"]

body:
    - type: checkboxes
      id: existing-issue
      attributes:
          label: Is there an existing issue for this?
          description: Please search to see if an issue already exists for the bug you encountered.
          options:
              - label: I have searched the existing issues
                required: true

    - type: input
      id: use-case
      attributes:
          label: To which use case does your bug report relate?
          placeholder: "#1"
      validations:
          required: false

    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: A clear and concise description of what the bug is.
          placeholder: e.g. "When a button is pressed, the application crashes."
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: What did you expect?
          description: A clear and concise description of what you expected to happen.
          placeholder: e.g. "The application should not crash."
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
