name: Use Case
description: Describe a use case for this project
title: "[Use Case]: <title>"
labels: ["use case"]

body:
  - type: input
    id: actor
    attributes:
      label: Who is the primary actor in this use case?
      description: The primary actor is the person or system that interacts with the system to achieve a goal.
      placeholder: e.g. "Project member"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the use case
      description: A clear and concise description of the use case.
      placeholder: e.g. "As a project member, I want to [...]"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: A clear and concise description of the acceptance criteria for this use case.
      placeholder: e.g. "When I [...], then [...]"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the use case!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
