name: Build

on:
    push:
        branches:
            - main
            - develop
    pull_request:

env:
    node_version: ${{ vars.NODE_VERSION }}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node_version }}

            - name: Install dependencies
              run: npm install

            - name: Build application
              run: npm run build

            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: build-artifact
                  path: .svelte-kit/output/
                  if-no-files-found: error
