name: Build

on:
    push:
        branches: ["develop"]
        tags: ["v*.*.*"]
    pull_request:

env:
    PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/

            - name: Build application
              run: npm run build

            - name: Archive build artifacts
              uses: actions/upload-artifact@v7
              if: ${{ !cancelled() }}
              with:
                  name: build-artifact
                  path: .svelte-kit/output/
                  if-no-files-found: error

    release:
        name: Release
        needs: build
        if: github.ref_type == 'tag'
        permissions:
            contents: write
        uses: SE-UUlm/snowballr-ci/.github/workflows/release.yml@v1
        with:
            artifact-name: build-artifact
            asset-path: snowballr-frontend-${{ github.ref_name }}.zip
            zip-assets: true
            target-branch: main
