name: Code Quality Checks

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    merge_group:
    workflow_dispatch:

env:
    node_version: ${{ vars.NODE_VERSION }}
    PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}

            - name: Run License Check
              run: npm run license-check

            - name: Linting
              run: npm run lint

    unit-test:
        name: Unit Testing with Vitest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}

            - name: Run unit tests
              run: npm run test:unit

            - name: Upload coverage report
              uses: actions/upload-artifact@v6
              if: ${{ !cancelled() }}
              with:
                  name: unit-code-coverage-report
                  path: coverage/
                  retention-days: 1
                  if-no-files-found: error

    integration-test:
        name: Integration Testing with Vitest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}

            - name: Run integration tests
              run: npm run test:integration

            - name: Upload coverage report
              uses: actions/upload-artifact@v6
              if: ${{ !cancelled() }}
              with:
                  name: integration-code-coverage-report
                  path: coverage/
                  retention-days: 1
                  if-no-files-found: error

    coverage-report:
        name: Code Coverage Report
        runs-on: ubuntu-latest
        needs: [unit-test, integration-test]
        permissions:
            pull-requests: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}

            - name: Download unit test coverage report
              uses: actions/download-artifact@v7
              with:
                  name: unit-code-coverage-report
                  path: coverage/unit

            - name: Download integration test coverage report
              uses: actions/download-artifact@v7
              with:
                  name: integration-code-coverage-report
                  path: coverage/integration

            # Now there are two coverage reports in the coverage folder
            # coverage
            # ├── integration
            # │   └── lcov.info
            # └── unit
            #     └── lcov.info

            - name: Install LCOV
              run: sudo apt install lcov

            - name: Combine coverage reports
              run: lcov -a coverage/unit/lcov.info -a coverage/integration/lcov.info --output-file final-lcov.info

            - name: Report code coverage
              uses: zgosalvez/github-actions-report-lcov@v5
              with:
                  coverage-files: final-lcov.info
                  artifact-name: code-coverage-report
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  update-comment: true

            - name: Upload coverage report
              uses: actions/upload-artifact@v6
              if: ${{ !cancelled() }}
              with:
                  name: final-code-coverage-report
                  path: ${{ github.workspace }}/final-lcov.info
                  retention-days: 1
                  if-no-files-found: error

    teamscale-upload:
        name: Teamscale Upload
        runs-on: ubuntu-latest
        needs: coverage-report
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Download coverage report
              uses: actions/download-artifact@v7
              with:
                  name: final-code-coverage-report
                  path: .

            - name: Teamscale Upload
              uses: SE-UUlm/snowballr-ci/src/teamscale-upload@v1.0.0
              with:
                  project: "d8724f02-e6d7-4d13-8f07-bdf631ceaf2e"
                  access-key: ${{ secrets.TEAMSCALE_ACCESS_KEY }}
                  format: LCOV
                  files: ${{ github.workspace }}/final-lcov.info

    check:
        name: Svelte Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}

            - name: Run all checks
              run: npm run check
