name: Deploy

on:
    push:
        branches: ["main", "develop"]
        tags: ["v*"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{github.repository}}
    CONTAINER_NAME: ${{ github.event.repository.name }} # only repository name

jobs:
    build-and-publish-docker-image:
        name: Build and Publish Docker Image
        runs-on: linux-sp
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # This step uses metadata-action to extract tags and labels that will be
            # applied to the specified image. The `id` "meta" allows the output of
            # this step to be referenced in a subsequent step. The `images` value
            # provides the base name for the tags and labels.
            # We add the following tags
            # - version tags: for v1.2.3 -> v1, v1.2, v1.2.3
            # - latest tags: for develop -> latest-dev; for main -> latest
            # - branch tags: just the branch name
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=semver,pattern={{version}},enable=${{ github.ref_type == 'tag' }}
                      type=semver,pattern={{major}}.{{minor}},enable=${{ github.ref_type == 'tag' }}
                      type=semver,pattern={{major}},enable=${{ github.ref_type == 'tag' }}
                      type=raw,value=latest-dev,enable=${{ github.ref_name == 'develop' }}
                      type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
                  flavor: |
                      latest=false

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v2
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-registry: true
