name: End-to-End Tests

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

env:
    PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}
    TESTS_PER_SHARD: ${{ vars.TESTS_PER_SHARD }}

jobs:
    determine-shards:
        name: Determine Number of Shards
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.create-matrix.outputs.matrix }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/

            - name: Create Shard Matrix
              id: create-matrix
              run: |
                  # Get total count of E2E tests
                  test_count="$(npx playwright test --list --reporter list | tail -n1 | sed -E 's/^Total: *([0-9]+).*/\1/')"
                  if ! [[ "$test_count" =~ ^[0-9]+$ ]]; then
                    echo "Error: Failed to extract a valid test count. Got: '$test_count'"
                    exit 1
                  fi

                  # Get number of shards (default to 1)
                  shards=$((test_count / ${{ env.TESTS_PER_SHARD }})); [ $shards -eq 0 ] && shards=1
                  echo "Dividing $test_count tests on $shards shards"

                  # Create Shard Matrix
                  shardArray=$(seq -s, 1 $shards | sed 's/,/","/g')
                  matrix=$(echo "{\"shard\": [\"$shardArray\"]}")
                  echo "Matrix: $matrix"
                  echo "matrix=$matrix" >> $GITHUB_OUTPUT

    ff-e2e-test:
        name: Fast-Failing End-to-End Testing with Playwright
        # Only run in PRs
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.body, '#e2e-run-all') }}
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs: determine-shards
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.determine-shards.outputs.matrix) }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: E2E-Setup
              uses: ./.github/workflows/e2e-setup/

            - name: Run only tests for changed code (fail fast)
              id: fail-fast-run
              run: npm run test:e2e -- --shard ${{ matrix.shard }}/${{ strategy.job-total }} --only-changed=origin/${{ github.base_ref }}

            - name: Archive Playwright report
              uses: actions/upload-artifact@v7
              if: ${{ !cancelled() }}
              with:
                  name: ff-playwright-report-${{ matrix.shard }}
                  path: e2e-report/
                  retention-days: 30

    e2e-test:
        name: Complete End-to-End Testing with Playwright
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '#e2e-run-all')) }}
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs: determine-shards
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.determine-shards.outputs.matrix) }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: E2E-Setup
              uses: ./.github/workflows/e2e-setup/

            - name: Run E2E tests
              run: npm run test:e2e -- --shard ${{ matrix.shard }}/${{ strategy.job-total }}

            - name: Archive Playwright report
              uses: actions/upload-artifact@v7
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report-${{ matrix.shard }}
                  path: e2e-report/
                  retention-days: 30
