name: Git Conventions

on:
    pull_request:
        branches:
            - develop

jobs:
    ensure-linear-history:
        name: Ensure Linear Git History
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Run Check
              uses: SE-UUlm/snowballr-ci/src/git_conventions/ensure_linear_history@feat/1-feature-add-initial-workflows
              with:
                  target-branch: develop
