name: Lighthouse

on:
    pull_request:
        types:
            - review_requested

env:
    node_version: ${{ vars.NODE_VERSION }}

jobs:
    lighthouse:
        name: Lighthouse Auditing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                  submodules: "recursive"

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}

            - name: Set up Docker Compose
              uses: docker/setup-compose-action@v1

            # We use the mock-local compose profile to run the frontend together with a dummy mock-backend
            - name: Run frontend with dummy mock-backend
              run: |
                  echo "PORT=5173" > .env
                  echo "RANDOMNESS_SEED=U25vd2JhbGxS" >> .env
                  docker compose --profile mock-local up -d --wait

            - name: Run Lighthouse
              run: npm run lighthouse:all -- --params="projectId=11,paperId=11-0"

            - name: Archive coverage report
              uses: actions/upload-artifact@v5
              with:
                  name: lighthouse-report
                  path: lighthouse-reports
                  if-no-files-found: error
